kargig/greek-adblockplus-filter

- void-gr-filters.txt
> clear a few 404 urls

- void-gr-filters.txt
2 ads in thepressproject.gr webpage.
> thepressproject.gr ads

- void-gr-filters.txt
stoiximan ad on sport24.gr (front page)
> sport24 ad

- void-gr-filters.txt
Hi,
Just a minor contribution for cretalive.gr.
> Remove ad banner from cretalive.gr

- void-gr-filters.txt
massive ad removal for kritikes-aggelies.gr
> kritikes-aggelies.gr

- void-gr-filters.txt
> sportena.com gone

- void-gr-filters.txt
Some rules for news portals in Crete.
> Update rules for some news portals in Crete

- void-gr-filters.txt
> Add rules for corfuland.gr

- void-gr-filters.txt
> Add rules for eviaportal.gr

- void-gr-filters.txt
> Update rules for Larissanet.gr

- void-gr-filters.txt
Blocked all annoying banner gif ads that made the browsing experience unbearable.
> Add rule for edu4u.gr

- void-gr-filters.txt
I also removed some rules because of their different implementation of ads.
> Add rules for thestival.gr

- void-gr-filters.txt
> Update rules for filadelfia-xalkidona.gr

- void-gr-filters.txt
> Add rules for realestatenews.gr

- void-gr-filters.txt
Χθες μου ήρθε ένα phishing email και καλά από την Εθνική Τράπεζα.
Το site είναι καλοφτιαγμένο και φοβάμαι θα την πατήσουν πολλοί.
https://goldenconcept.ir//wp-config/config/www.nbg.gr/nbgi-bank-National-Bank-Greece/nbgi-bank-National-Bank-Greece/
Θα μπορούσαμε μήπως να το προσθέσουμε στη λίστα για να γλιτώσουμε έστω και ελάχιστους από την ταλαιπωρία;
> Add goldenconcept.ir

- void-gr-filters.txt
> Add rules for insomnia.gr

- void-gr-filters.txt
parianostypos.gr
fonitisparou.gr
> added paros-specific rules

- void-gr-filters.txt
This pull request vanishes everything related to ads and tracking.
Closes #75
> Add rules for gazzetta.gr

- void-gr-filters.txt
> Add rules for filoitexnisfilosofias.com

- void-gr-filters.txt
Blocking two ad cdn's, plus a couple of cosmetic filters for randomly generated id names.
> Rules for ads found on parianostypos.gr

- void-gr-filters.txt
Vanishes ads from:
https://www.car.gr/plot/agora
https://www.car.gr/classifieds/cars
etc.
> Add rules for car.gr

- void-gr-filters.txt
> Clean entries about non-existent domains

- void-gr-filters.txt
> Add rules for serraikanea.gr

- void-gr-filters.txt
> Add rule for insomnia.gr

- void-gr-filters.txt
> Remove problematic rule from insomnia.gr

- void-gr-filters.txt
Block sponsored items from `skroutz.gr`
Fixes: #112
> Add skroutz.gr sponsored items

- void-gr-filters.txt
added rule to remove sponsored listings (see also #114 )
> bestprice.gr sponsored listings

- void-gr-filters.txt
This was blocking legitimate content
Fixes #126
> Fix meteo.gr

- void-gr-filters.txt
Fixes https://github.com/kargig/greek-adblockplus-filter/issues/149
> Block ads from kavalapoint.gr

- void-gr-filters.txt
Removed the entries for the FQDNs below:
axiabanners.exodus.gr
call.theowl.gr
educate.theowl.gr
gpoint.gpoint.com.gr
promo.gpoint.com.gr
promos.pathfinder.gr
switch.statman.gr
> Removed entries with dead FQDNs
